package com.exponentiallydigital.pia_wireguard_cfga

import android.content.ClipboardManager
import android.content.Context
import android.content.pm.PackageInfo
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.view.WindowManager
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
        window.setFlags(
           WindowManager.LayoutParams.FLAG_SECURE,
           WindowManager.LayoutParams.FLAG_SECURE
        )
        super.onCreate(savedInstanceState)
    }

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        // MUST come first: this is where the generated plugin registrant runs. Skipping it
        // silently breaks path_provider, share_plus, url_launcher and package_info_plus.
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
            .setMethodCallHandler { call, result ->
                when (call.method) {
                    METHOD_GET_BUILD_INFO -> result.success(collectBuildInfo())
                    else -> result.notImplemented()
                }
            }

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CLIPBOARD_CHANNEL)
            .setMethodCallHandler { call, result ->
                when (call.method) {
                    METHOD_CLEAR_CLIPBOARD -> clearClipboard(result)
                    else -> result.notImplemented()
                }
            }
    }

    override fun cleanUpFlutterEngine(flutterEngine: FlutterEngine) {
        // Detach the handlers so the engine does not retain this Activity.
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
            .setMethodCallHandler(null)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CLIPBOARD_CHANNEL)
            .setMethodCallHandler(null)
        super.cleanUpFlutterEngine(flutterEngine)
    }

    /**
     * Empties the system clipboard silently.
     *
     * Dart used to do this by copying an empty string, but Android shows its clipboard preview
     * for any copy, so exiting the app - or the 60-second countdown expiring - flashed a
     * "copied" popup at a user who had not copied anything.
     *
     * clearPrimaryClip() arrived at API 28 (P) and minSdk here is 24. Below that there is no
     * silent option, so this reports an error and Dart falls back to writing an empty string,
     * popup and all. Any failure is reported the same way rather than swallowed, so the
     * clipboard is emptied one way or the other.
     */
    private fun clearClipboard(result: MethodChannel.Result) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.P) {
            result.error(ERROR_UNSUPPORTED, "clearPrimaryClip() requires API 28", null)
            return
        }
        val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
        if (clipboard == null) {
            result.error(ERROR_UNAVAILABLE, "No ClipboardManager", null)
            return
        }
        clipboard.clearPrimaryClip()
        result.success(null)
    }

    /**
     * Build- and run-time provenance for the About screen (lib/screens/about_screen.dart).
     *
     * Every value is a String so the platform channel hands Dart a plain Map<String, String>
     * -- no mixed-type StandardMessageCodec surprises and no per-key casting in Dart.
     *
     * Compile-time values come from BuildConfig (see android/app/build.gradle.kts);
     * BUILD_TYPE / VERSION_NAME / VERSION_CODE / APPLICATION_ID / DEBUG are generated by AGP
     * itself once buildFeatures.buildConfig is enabled.
     */
    private fun collectBuildInfo(): Map<String, String> {
        var versionName = UNKNOWN
        var buildNumber = UNKNOWN
        try {
            val info = ownPackageInfo()
            versionName = info.versionName ?: UNKNOWN
            buildNumber = longVersionCodeOf(info).toString()
        } catch (_: PackageManager.NameNotFoundException) {
            // Cannot normally happen when querying our own package, but a partially removed
            // or heavily customised ROM install can still throw. Fall through with UNKNOWN
            // rather than crashing the About screen.
        }

        return mapOf(
            "versionName" to versionName,
            "buildNumber" to buildNumber,
            "installer" to installerLabel(),
            "buildTimestamp" to BuildConfig.BUILD_TIMESTAMP,
            "buildType" to BuildConfig.BUILD_TYPE, // AGP-generated: debug / profile / release
            "commitHash" to BuildConfig.GIT_COMMIT_HASH,
            "commitDate" to BuildConfig.GIT_COMMIT_DATE,
            "gitBranch" to BuildConfig.GIT_BRANCH,
            "runnerId" to BuildConfig.CI_RUNNER_ID,
            "cpuAbi" to (Build.SUPPORTED_ABIS?.firstOrNull() ?: UNKNOWN),
            "osVersion" to osVersionLabel(),
            "compileSdk" to BuildConfig.COMPILE_SDK,
            "kotlinVersion" to BuildConfig.KOTLIN_VERSION
        )
    }

    /**
     * getPackageInfo(String, Int) was deprecated at API 33 (TIRAMISU) in favour of the
     * PackageInfoFlags overload. The SDK_INT check is inline so lint's NewApi is satisfied
     * without pulling in androidx.annotation's @RequiresApi.
     */
    @Suppress("DEPRECATION")
    private fun ownPackageInfo(): PackageInfo =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            packageManager.getPackageInfo(packageName, PackageManager.PackageInfoFlags.of(0L))
        } else {
            packageManager.getPackageInfo(packageName, 0)
        }

    /**
     * PackageInfo.longVersionCode arrived at API 28 (P); minSdk here is 24, so the legacy int
     * field is still reachable.
     *
     * androidx.core's PackageInfoCompat would do exactly this, and androidx.core:core IS on
     * the compile classpath -- but only transitively, via the Flutter embedding. This module
     * deliberately has no dependencies {} block, and declaring androidx.core would force the
     * STRICT lockfiles to be regenerated for a two-line branch. Not worth it.
     */
    @Suppress("DEPRECATION")
    private fun longVersionCodeOf(info: PackageInfo): Long =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            info.longVersionCode
        } else {
            info.versionCode.toLong()
        }

    /** Human-readable install source, e.g. "Google Play" or "adb / shell". */
    private fun installerLabel(): String {
        val installerPackage: String? =
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                    // getInstallerPackageName() was deprecated at API 30 (R) in favour of
                    // getInstallSourceInfo(). installingPackageName is the package that
                    // requested the install; it is null once that installer is itself gone.
                    packageManager.getInstallSourceInfo(packageName).installingPackageName
                } else {
                    legacyInstallerPackageName()
                }
            } catch (_: PackageManager.NameNotFoundException) {
                null
            }

        if (installerPackage.isNullOrBlank()) {
            // `adb install`, `flutter run`, and sideloads whose installer has since been
            // removed all land here. This is the normal case for a local debug build.
            return "Sideloaded (no install source)"
        }
        // An unrecognised installer falls back to its raw package name -- more useful on an
        // About screen than collapsing everything unknown into a single label.
        return INSTALLER_LABELS[installerPackage] ?: installerPackage
    }

    /**
     * Deprecated at API 30 and only ever reached on API 24..29, so the suppression is scoped
     * to this one-line helper instead of blanketing the caller.
     */
    @Suppress("DEPRECATION")
    private fun legacyInstallerPackageName(): String? =
        packageManager.getInstallerPackageName(packageName)

    private fun osVersionLabel(): String {
        // RELEASE_OR_CODENAME (API 30+) reports e.g. "VanillaIceCream" on preview builds,
        // where plain RELEASE is the useless placeholder "REL".
        val release =
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                Build.VERSION.RELEASE_OR_CODENAME
            } else {
                Build.VERSION.RELEASE
            } ?: UNKNOWN
        return "Android $release (API ${Build.VERSION.SDK_INT})"
    }

    private companion object {
        const val CHANNEL = "com.exponentiallydigital.pia_wireguard_cfga/build_info"
        const val METHOD_GET_BUILD_INFO = "getBuildInfo"
        // Mirrored in lib/clipboard_service.dart; a test fails if the two drift apart.
        const val CLIPBOARD_CHANNEL = "com.exponentiallydigital.pia_wireguard_cfga/clipboard"
        const val METHOD_CLEAR_CLIPBOARD = "clearClipboard"
        const val ERROR_UNSUPPORTED = "unsupported"
        const val ERROR_UNAVAILABLE = "unavailable"
        const val UNKNOWN = "unknown"

        val INSTALLER_LABELS: Map<String, String> = mapOf(
            "com.android.vending" to "Google Play",
            "com.google.android.feedback" to "Google Play (legacy)",
            "com.android.packageinstaller" to "System package installer",
            "com.google.android.packageinstaller" to "System package installer",
            "com.google.android.permissioncontroller" to "System package installer",
            "com.miui.packageinstaller" to "MIUI package installer",
            "com.samsung.android.packageinstaller" to "Samsung package installer",
            "com.android.shell" to "adb / shell",
            "org.fdroid.fdroid" to "F-Droid",
            "org.fdroid.fdroid.privileged" to "F-Droid (privileged)",
            "com.machiav3lli.fdroid" to "Neo Store",
            "com.looker.droidify" to "Droid-ify",
            "dev.imranr.obtainium" to "Obtainium",
            "com.aurora.store" to "Aurora Store",
            "com.amazon.venezia" to "Amazon Appstore",
            "com.sec.android.app.samsungapps" to "Galaxy Store",
            "com.huawei.appmarket" to "Huawei AppGallery"
        )
    }
}
