sonar.projectKey=ExponentiallyDigital_cfg-pia-wg
sonar.organization=exponentiallydigital
sonar.sources=lib
sonar.tests=test
sonar.scanner.skipJreProvisioning=true
sonar.dart.lcov.reportPaths=coverage/lcov.info