// fail_closed_guard.dart - keeps a device pinned to a tunnel off the internet while that tunnel is down.
//
// This program is free software: you can redistribute it and/or modify it under the terms
// of the GNU General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see https://www.gnu.org/licenses/.
//
// Copyright (C) 2026 Andrew Newbury.
//
// Stock firmware has no kill switch, and on its own it does not quite fail closed. Measured
// 2026-09-24 with a device pinned to wgc1 (ARCHITECTURE.md "The fail-closed guard"):
//
//   - a tunnel whose server stops answering blocks the device, which is right;
//   - a watchdog rebuild let one reply out through the default connection, in the second the
//     firmware spent rebuilding the tunnel's routing table;
//   - a DISABLE let the device out for as long as the tunnel was off, through the default
//     connection, and in the clear when that is the plain internet.
//
// A route in the tunnel's table cannot close that gap: the firmware rebuilds the table on every
// restart, and the table carries a copy of the WAN default route, which always wins. Rules survive,
// because the firmware only ever removes the ones it made. So the guard is two rules per pinned
// device, kept by one script that the app, every watchdog run and the boot hook all call.
//
// Stock only. Merlin has a real kill switch, and device assignment is a stock feature here.

import 'firmware.dart' show kRouterAppDir;
import 'router_watchdog.dart' show heredocWriteCommands, writtenByteCount;

/// Where the guard script lives on the router. The watchdog script and the boot hook call it by
/// this path, and only if it is there.
const String kGuardScriptPath = '$kRouterAppDir/guard.sh';

/// The guard script. Idempotent: run it as often as you like, and it changes only what is wrong.
///
/// Priorities 90 and 91 are the app's alone - the firmware's per-device rules sit at 100 and its
/// default connection at 10000 - so anything found at 90 or 91 is the guard's to keep or remove.
const String kGuardScript = r'''#!/bin/sh
# guard.sh - auto-generated by cfg-pia-wg; *do* *not* edit.
#
# Keeps every device pinned to a WireGuard tunnel off the internet whenever that tunnel is not
# carrying it: expired, being rebuilt, or switched off. Two rules per pinned device:
#
#   90: from <ip> lookup <table> suppress_prefixlength 0   the tunnel's own routes, never a default
#   91: from <ip> blackhole                                anything else is dropped
#
# Rules and not routes: the firmware rebuilds a tunnel's table on every restart, but leaves rules
# it did not make alone. The table also holds a copy of the WAN default route, and
# suppress_prefixlength 0 is what refuses it.
#
# Worked out afresh from vpnc_dev_policy_list on every run, so a pin made or removed in the web
# interface is followed too. "guard.sh clear" removes every guard rule.

# Two watchdogs can start in the same second. One run at a time, or both add the same rule.
LOCK="${GUARD_LOCK:-/tmp/cfg-pia-wg-guard.lock}"
W=0
until mkdir "$LOCK" 2>/dev/null; do
  W=$((W + 1))
  # Ten seconds is far longer than a run takes, so a lock that old was left by a killed run.
  if [ "$W" -ge 10 ]; then rm -rf "$LOCK"; mkdir "$LOCK" 2>/dev/null; break; fi
  sleep 1
done
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

say() { logger -t cfg-pia-wg "$1"; }

# Every "ip>table" that should be guarded: an enabled policy record naming a WireGuard profile.
WANT=""
if [ "$1" != "clear" ]; then
  TABLES=" $(nvram get vpnc_clientlist | tr '<' '\n' | awk -F'>' '$2 == "WireGuard" && $7 != "" {printf "%s ", $7}')"
  WANT="$(nvram get vpnc_dev_policy_list | tr '<' '\n' | awk -F'>' -v t="$TABLES" '$1 == "1" && $2 != "" && index(t, " " $4 " ") {print $2 ">" $4}')"
fi

held90() { ip rule show | awk '$1 == "90:" {ip = ""; t = ""; for (i = 2; i < NF; i++) {if ($i == "from") ip = $(i + 1); if ($i == "lookup") t = $(i + 1)} if (ip != "") print ip ">" t}'; }
held91() { ip rule show | awk '$1 == "91:" {for (i = 2; i < NF; i++) if ($i == "from") print $(i + 1)}'; }
wanted_ip() { echo "$WANT" | awk -F'>' -v ip="$1" '$1 == ip {f = 1} END {exit !f}'; }
drop() { N=0; while [ "$N" -lt 8 ] && ip rule del from "$1" priority "$2" 2>/dev/null; do N=$((N + 1)); done; }
slot_of() { nvram get vpnc_clientlist | tr '<' '\n' | awk -F'>' -v t="$1" '$7 == t {print "wgc" $3; exit}'; }

# Take away what is no longer wanted, wanted differently, or held more than once.
H90="$(held90)"
for E in $(echo "$H90" | sort -u); do
  if ! echo "$WANT" | grep -qxF "$E" || [ "$(echo "$H90" | grep -cxF "$E")" -gt 1 ]; then
    drop "${E%>*}" 90
    wanted_ip "${E%>*}" || say "Fail-closed guard removed for ${E%>*}"
  fi
done
H91="$(held91)"
for IP in $(echo "$H91" | sort -u); do
  if ! wanted_ip "$IP" || [ "$(echo "$H91" | grep -cxF "$IP")" -gt 1 ]; then drop "$IP" 91; fi
done

# Add what is missing. The drop rule goes in first, so a half-added guard fails closed, not open.
FAIL=0
H90="$(held90)"
H91="$(held91)"
for E in $WANT; do
  IP="${E%>*}"
  T="${E#*>}"
  echo "$H91" | grep -qxF "$IP" || ip rule add from "$IP" blackhole priority 91 || FAIL=$((FAIL + 1))
  if ! echo "$H90" | grep -qxF "$E"; then
    if ip rule add from "$IP" lookup "$T" suppress_prefixlength 0 priority 90; then
      say "Fail-closed guard on for $IP ($(slot_of "$T"))"
    else
      FAIL=$((FAIL + 1))
    fi
  fi
done

echo "guarded $(echo "$WANT" | grep -c .)"
[ "$FAIL" -eq 0 ] || { echo "failed $FAIL"; say "Fail-closed guard: $FAIL rule(s) could not be added"; exit 1; }
exit 0
''';

typedef GuardLog = void Function(String message, {bool isError, bool isSuccess, bool isWarning});

/// Installs and runs [kGuardScript] over an existing SSH session.
///
/// Takes the caller's own read and run so it goes through the same command path, logging and test
/// fakes as everything else: [read] never throws, [run] throws on a non-zero exit.
class FailClosedGuard {
  FailClosedGuard({required this.read, required this.run, this.onLog});

  final Future<String> Function(String cmd) read;
  final Future<String> Function(String cmd) run;
  final GuardLog? onLog;

  /// Puts the script in place if it is missing or out of date, runs it, and returns how many
  /// devices it now guards.
  ///
  /// Never throws: a guard that could not be put in place must not stop the action it follows,
  /// whether that is an assignment, a DISABLE or a DELETE. It returns null instead, after saying
  /// plainly in the app log what that means. [quiet] leaves out the line reporting success, for
  /// callers that run it on every screen refresh.
  Future<int?> ensure({bool quiet = false}) async {
    try {
      await install();
      final out = await run("'$kGuardScriptPath'");
      final count = int.tryParse(RegExp(r'guarded (\d+)').firstMatch(out)?.group(1) ?? '');
      if (!quiet && count != null && count > 0) {
        onLog?.call('Fail-closed guard in place for $count pinned device${count == 1 ? '' : 's'}.');
      }
      return count;
    } catch (e) {
      onLog?.call(
        'The fail-closed guard could not be put in place ($e). Until it is, a device pinned to a tunnel '
        'can reach the internet through the default connection while that tunnel is down.',
        isWarning: true,
      );
      return null;
    }
  }

  /// Writes the script only when what is on the router differs, so an unchanged guard costs one
  /// read and no flash write. Verified by size afterwards, as every other file the app writes is.
  Future<void> install() async {
    // `|| true`: on a router that has never had the guard there is no file, and a read that exits
    // non-zero is logged as a failed command - which is how a normal first install used to read.
    final current = await read("cat '$kGuardScriptPath' 2>/dev/null || true");
    if (current.trim() == kGuardScript.trim()) return;
    await run("mkdir -p '$kRouterAppDir'");
    for (final cmd in heredocWriteCommands(kGuardScriptPath, kGuardScript)) {
      await run(cmd);
    }
    await run("chmod 755 '$kGuardScriptPath'");
    final expected = writtenByteCount(kGuardScript);
    final size = int.tryParse((await read("wc -c < '$kGuardScriptPath' 2>/dev/null | tr -d ' '")).trim()) ?? 0;
    if (size != expected) {
      throw Exception('the router holds $size of the $expected bytes of $kGuardScriptPath');
    }
  }

  /// Removes every guard rule. Used by UNINSTALL, before the script goes with the app's folder.
  Future<void> clear() => read("[ -x '$kGuardScriptPath' ] && '$kGuardScriptPath' clear");
}
