// fail_closed_guard.dart - keeps a device pinned to a tunnel off the internet while that tunnel is down.
//
// This program is free software: you can redistribute it and/or modify it under the terms
// of the GNU General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see https://www.gnu.org/licenses/.
//
// Copyright (C) 2026 Andrew Newbury.
//
// Stock firmware has no kill switch, and on its own it does not quite fail closed. Measured
// 2026-09-24 with a device pinned to wgc1 (ARCHITECTURE.md "The fail-closed guard"):
//
//   - a tunnel whose server stops answering blocks the device, which is right;
//   - a watchdog rebuild let one reply out through the default connection, in the second the
//     firmware spent rebuilding the tunnel's routing table;
//   - a DISABLE let the device out for as long as the tunnel was off, through the default
//     connection, and in the clear when that is the plain internet.
//
// A route in the tunnel's table cannot close that gap: the firmware rebuilds the table on every
// restart, and the table carries a copy of the WAN default route, which always wins. Rules survive,
// because the firmware only ever removes the ones it made. So the guard is two rules per pinned
// device, kept by one script that the app, every watchdog run and the boot hook all call.
//
// Stock only. Merlin has a real kill switch, and device assignment is a stock feature here.

import 'firmware.dart' show kRouterAppDir, kS50Path, kStockBootDir, originalScriptBackupPath;
import 'router_watchdog.dart' show heredocWriteCommands, writtenByteCount;
import 's50_template.dart' show buildS50Script, extractS50CruLines;

/// Where the guard script lives on the router. The watchdog script and the boot hook call it by
/// this path, and only if it is there.
const String kGuardScriptPath = '$kRouterAppDir/guard.sh';

/// The cron entry that runs the guard every minute while any device is pinned (ID-316).
const String kGuardCronTag = 'cfg_pia_wg_guard';
const String kGuardCronLine = 'cru a $kGuardCronTag "* * * * *" $kGuardScriptPath';

/// Marks the app's own copy of an init script; the same line RouterWatchdog looks for.
const String kOurScriptSignature = 'auto-generated by cfg-pia-wg';

/// The guard script. Idempotent: run it as often as you like, and it changes only what is wrong.
///
/// Priorities 90 and 91 are the app's alone - the firmware's per-device rules sit at 100 and its
/// default connection at 10000 - so anything found at 90 or 91 is the guard's to keep or remove.
const String kGuardScript = r'''#!/bin/sh
# guard.sh - auto-generated by cfg-pia-wg; *do* *not* edit.
#
# Keeps every device pinned to a WireGuard tunnel off the internet whenever that tunnel is not
# carrying it: expired, being rebuilt, or switched off. Two rules per pinned device:
#
#   90: from <ip> lookup <table> suppress_prefixlength 0   the tunnel's own routes, never a default
#   91: from <ip> blackhole                                anything else is dropped
#
# Rules and not routes: the firmware rebuilds a tunnel's table on every restart, but leaves rules
# it did not make alone. The table also holds a copy of the WAN default route, and
# suppress_prefixlength 0 is what refuses it.
#
# Worked out afresh from vpnc_dev_policy_list on every run, so a pin made or removed in the web
# interface is followed too. "guard.sh clear" removes every guard rule.

# Two watchdogs can start in the same second. One run at a time, or both add the same rule.
LOCK="${GUARD_LOCK:-/tmp/cfg-pia-wg-guard.lock}"
W=0
until mkdir "$LOCK" 2>/dev/null; do
  W=$((W + 1))
  # Ten seconds is far longer than a run takes, so a lock that old was left by a killed run.
  if [ "$W" -ge 10 ]; then rm -rf "$LOCK"; mkdir "$LOCK" 2>/dev/null; break; fi
  sleep 1
done
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

say() { logger -t cfg-pia-wg "$1"; }

# Every "ip>table" that should be guarded: an enabled policy record naming a WireGuard profile.
WANT=""
# And every address pinned to a profile that no longer exists at all: deleted in the web interface,
# which leaves the pin behind. The firmware's rule sends it to an empty table and on to the default
# connection, so it gets rule 91 alone: no tunnel to use, so nothing. A pin to Internet is index 0,
# and a pin to an OpenVPN profile names a profile that exists; neither is caught.
ORPHAN=""
if [ "$1" != "clear" ]; then
  TABLES=" $(nvram get vpnc_clientlist | tr '<' '\n' | awk -F'>' '$2 == "WireGuard" && $7 != "" {printf "%s ", $7}')"
  WANT="$(nvram get vpnc_dev_policy_list | tr '<' '\n' | awk -F'>' -v t="$TABLES" '$1 == "1" && $2 != "" && index(t, " " $4 " ") {print $2 ">" $4}')"
  ALLT=" $(nvram get vpnc_clientlist | tr '<' '\n' | awk -F'>' '$7 != "" {printf "%s ", $7}')"
  ORPHAN="$(nvram get vpnc_dev_policy_list | tr '<' '\n' | awk -F'>' -v t="$ALLT" '$1 == "1" && $2 != "" && $4 != "" && $4 != "0" && !index(t, " " $4 " ") {print $2}')"
fi

held90() { ip rule show | awk '$1 == "90:" {ip = ""; t = ""; for (i = 2; i < NF; i++) {if ($i == "from") ip = $(i + 1); if ($i == "lookup") t = $(i + 1)} if (ip != "") print ip ">" t}'; }
held91() { ip rule show | awk '$1 == "91:" {for (i = 2; i < NF; i++) if ($i == "from") print $(i + 1)}'; }
wanted_ip() { echo "$WANT" | awk -F'>' -v ip="$1" '$1 == ip {f = 1} END {exit !f}'; }
orphan_ip() { echo "$ORPHAN" | grep -qxF "$1"; }
drop() { N=0; while [ "$N" -lt 8 ] && ip rule del from "$1" priority "$2" 2>/dev/null; do N=$((N + 1)); done; }
slot_of() { nvram get vpnc_clientlist | tr '<' '\n' | awk -F'>' -v t="$1" '$7 == t {print "wgc" $3; exit}'; }
# The device as DEVICES names it, then its address: the user's name, else the detected
# one, else the address alone (ID-262).
name_of() {
  M="$(nvram get dhcp_staticlist | tr '<' '\n' | awk -F'>' -v a="$1" '$2 == a {print toupper($1); exit}')"
  D=""
  [ -n "$M" ] && D="$(nvram get custom_clientlist | tr '<' '\n' | awk -F'>' -v m="$M" 'toupper($2) == m && $1 != "" {print $1; exit}')"
  [ -z "$D" ] && [ -n "$M" ] && [ -x /jffs/cfg-pia-wg/jq ] && D="$(/jffs/cfg-pia-wg/jq -r --arg m "$M" 'to_entries[] | select((.key | ascii_upcase) == $m) | .value.name // empty' 2>/dev/null < /jffs/nmp_cl_json.js | head -1)"
  echo "${D:+$D }$1"
}

# A 90 rule without suppress_prefixlength 0 hands the device the WAN default the firmware copies
# into the tunnel's table: no guard at all. Drop any such rule; the loop below adds the right one.
for IP in $(ip rule show | awk '$1 == "90:" && $0 !~ /suppress_prefixlength 0/ {for (i = 2; i < NF; i++) if ($i == "from") print $(i + 1)}' | sort -u); do
  drop "$IP" 90
done

# Take away what is no longer wanted, wanted differently, or held more than once.
H90="$(held90)"
for E in $(echo "$H90" | sort -u); do
  if ! echo "$WANT" | grep -qxF "$E" || [ "$(echo "$H90" | grep -cxF "$E")" -gt 1 ]; then
    drop "${E%>*}" 90
    wanted_ip "${E%>*}" || say "Fail-closed guard removed for $(name_of "${E%>*}")"
  fi
done
H91="$(held91)"
for IP in $(echo "$H91" | sort -u); do
  if ! { wanted_ip "$IP" || orphan_ip "$IP"; } || [ "$(echo "$H91" | grep -cxF "$IP")" -gt 1 ]; then drop "$IP" 91; fi
done

# Add what is missing. The drop rule goes in first, so a half-added guard fails closed, not open.
FAIL=0
H90="$(held90)"
H91="$(held91)"
for E in $WANT; do
  IP="${E%>*}"
  T="${E#*>}"
  echo "$H91" | grep -qxF "$IP" || ip rule add from "$IP" blackhole priority 91 || FAIL=$((FAIL + 1))
  if ! echo "$H90" | grep -qxF "$E"; then
    if ip rule add from "$IP" lookup "$T" suppress_prefixlength 0 priority 90; then
      say "Fail-closed guard on for $(name_of "$IP") ($(slot_of "$T"))"
    else
      FAIL=$((FAIL + 1))
    fi
  fi
done
H91="$(held91)"
for IP in $ORPHAN; do
  echo "$H91" | grep -qxF "$IP" && continue
  if ip rule add from "$IP" blackhole priority 91; then
    say "Fail-closed guard: $(name_of "$IP") is pinned to a VPN profile that no longer exists, so it is kept off the internet"
  else
    FAIL=$((FAIL + 1))
  fi
done

# The addresses a tunnel's table sends out the WAN (ID-347). The firmware keeps host and subnet
# routes there via the WAN for the router's own DNS servers, the tunnel's PIA server and the ISP's
# subnet, and suppress_prefixlength 0 only refuses the default, so rule 90 sent a pinned device
# to those addresses outside the tunnel - with the tunnel up or down. Measured 2026-09-30: a pinned
# phone's Private DNS at 1.1.1.2 left from the real IP. For each such address X:
#
#   88: from <ip> to X lookup <200 + slot>   a table holding only the tunnel's two /1 routes
#   89: from <ip> to X blackhole             reached when the tunnel is down and that table is empty
#
# The /1 routes vanish with the interface and come back on the next run - every minute from cron -
# so in between, X is blocked rather than let out.
tunnel_only() { echo $((200 + ${1#wgc})); }
wan_routes() { ip route show table "$1" | awk '$1 != "default" && $0 !~ / dev (wgc|br|lo|wgs)[0-9]* / {print $1}'; }
W88=""; W89=""
for E in $WANT; do
  IP="${E%>*}"; T="${E#*>}"; IF="$(slot_of "$T")"
  [ -n "$IF" ] || continue
  TT="$(tunnel_only "$IF")"
  if ip -o link show up | grep -q " $IF:"; then
    ip route replace 0.0.0.0/1 dev "$IF" table "$TT" 2>/dev/null
    ip route replace 128.0.0.0/1 dev "$IF" table "$TT" 2>/dev/null
  fi
  for X in $(wan_routes "$T"); do
    W88="$W88 $IP>$X>$TT"; W89="$W89 $IP>$X"
  done
done
held() { ip rule show | awk -v p="$1:" '$1 == p {f = ""; to = ""; t = ""; for (i = 2; i < NF; i++) {if ($i == "from") f = $(i + 1); if ($i == "to") to = $(i + 1); if ($i == "lookup") t = $(i + 1)} print f ">" to (t == "" ? "" : ">" t)}'; }
in_list() { echo " $2 " | grep -qF " $1 "; }
for R in $(held 88); do in_list "$R" "$W88" || { F="${R%%>*}"; R2="${R#*>}"; ip rule del from "$F" to "${R2%>*}" priority 88 2>/dev/null; }; done
for R in $(held 89); do in_list "$R" "$W89" || ip rule del from "${R%>*}" to "${R#*>}" priority 89 2>/dev/null; done
H88=" $(held 88 | tr '\n' ' ') "; H89=" $(held 89 | tr '\n' ' ') "
# The blackhole first, as for 90 and 91, so a half-added pair fails closed.
for R in $W89; do in_list "$R" "$H89" || ip rule add from "${R%>*}" to "${R#*>}" blackhole priority 89 || FAIL=$((FAIL + 1)); done
for R in $W88; do
  in_list "$R" "$H88" && continue
  F="${R%%>*}"; R2="${R#*>}"
  ip rule add from "$F" to "${R2%>*}" lookup "${R2#*>}" priority 88 || FAIL=$((FAIL + 1))
done
[ "$1" = "clear" ] && for N in 1 2 3 4 5; do ip route flush table $((200 + N)) 2>/dev/null; done

# Counted from the kernel, not from what was asked for (ID-320): a device is guarded when it
# holds exactly one 90 rule with suppress_prefixlength 0, one 91 blackhole, and an 89 for every
# address its tunnel's table sends out the WAN.
TOTAL=0; OK=0
for E in $WANT; do
  IP="${E%>*}"; T="${E#*>}"; TOTAL=$((TOTAL + 1))
  [ "$(ip rule show | grep -c "^90:.*from $IP lookup $T suppress_prefixlength 0")" = 1 ] || continue
  [ "$(ip rule show | grep -c "^91:.*from $IP blackhole")" = 1 ] || continue
  MISS=0
  for X in $(wan_routes "$T"); do ip rule show | grep -q "^89:.*from $IP to $X blackhole" || MISS=1; done
  [ "$MISS" = 0 ] && OK=$((OK + 1))
done
for IP in $ORPHAN; do
  TOTAL=$((TOTAL + 1))
  [ "$(ip rule show | grep -c "^91:.*from $IP blackhole")" = 1 ] && OK=$((OK + 1))
done
echo "guarded $OK of $TOTAL"
[ "$FAIL" -eq 0 ] || { echo "failed $FAIL"; say "Fail-closed guard: $FAIL rule(s) could not be added"; exit 1; }
exit 0
''';

typedef GuardLog = void Function(String message, {bool isError, bool isSuccess, bool isWarning});

/// Installs and runs [kGuardScript] over an existing SSH session.
///
/// Takes the caller's own read and run so it goes through the same command path, logging and test
/// fakes as everything else: [read] never throws, [run] throws on a non-zero exit.
class FailClosedGuard {
  FailClosedGuard({required this.read, required this.run, this.onLog});

  final Future<String> Function(String cmd) read;
  final Future<String> Function(String cmd) run;
  final GuardLog? onLog;

  /// Puts the script in place if it is missing or out of date, runs it, and returns how many
  /// devices it now guards.
  ///
  /// Never throws: a guard that could not be put in place must not stop the action it follows,
  /// whether that is an assignment, a DISABLE or a DELETE. It returns null instead, after saying
  /// plainly in the app log what that means. [quiet] leaves out the line reporting success, for
  /// callers that run it on every screen refresh.
  Future<int?> ensure({bool quiet = false}) async {
    try {
      await install();
      final out = await run("'$kGuardScriptPath'");
      // "guarded N of M": N is what the kernel holds, counted after the run, not what was asked for
      // (ID-320). An older script says only "guarded N".
      final m = RegExp(r'guarded (\d+)(?: of (\d+))?').firstMatch(out);
      final count = int.tryParse(m?.group(1) ?? '');
      final total = int.tryParse(m?.group(2) ?? '') ?? count;
      if (count != null && total != null && count < total) {
        onLog?.call(
          'The fail-closed guard is complete for only $count of $total pinned devices. Until it is, the others '
          'can reach the internet outside their tunnel.',
          isWarning: true,
        );
      } else if (!quiet && count != null && count > 0) {
        onLog?.call('Fail-closed guard in place for $count pinned device${count == 1 ? '' : 's'}.');
      }
      // No count means the run's output was lost, not that nothing is pinned: leave the cron and
      // boot hook as they are rather than remove them from under pinned devices.
      if (total == null) return count;
      await _persist(total);
      return count;
    } catch (e) {
      onLog?.call(
        'The fail-closed guard could not be put in place ($e). Until it is, a device pinned to a tunnel '
        'can reach the internet through the default connection while that tunnel is down.',
        isWarning: true,
      );
      return null;
    }
  }

  /// Keeps the guard running without the app, whenever any device is pinned (ID-315, ID-316).
  ///
  /// Until build 480 only a watchdog deploy wrote the boot hook and nothing re-ran the guard between
  /// watchdog runs, so a router with pins but no watchdog had no guard at all after a reboot, and a
  /// firmware action that wipes rules (a web-interface VPN Fusion apply, `restart_net_and_phy`) left
  /// it off until the app was next used. Now: a cron entry runs it every minute, and the boot hook
  /// puts that entry back and runs the guard at boot. Both go when the last pin does.
  Future<void> _persist(int pinned) async {
    final hasCron = (await read("cru l | grep -c '#$kGuardCronTag#'")).trim() != '0';
    if (pinned == 0) {
      if (hasCron) await run('cru d $kGuardCronTag');
      return;
    }
    if (!hasCron) await run(kGuardCronLine);
    // The boot hook lives where stock runs it: Download Master's init directory, on USB storage.
    if ((await read("[ -d '$kStockBootDir' ] && echo yes || echo no")).trim() != 'yes') {
      onLog?.call(
        'The fail-closed guard will not survive a reboot: $kStockBootDir is missing, so the app has no boot hook. '
        'Install Download Master (README section 4) and leave it installed. After a reboot, until the app is next '
        'used, pinned devices can reach the internet outside their tunnel whenever it is down.',
        isWarning: true,
      );
      return;
    }
    final existing = await read("cat '$kS50Path' 2>/dev/null || true");
    final ours = existing.contains(kOurScriptSignature);
    final lines = ours ? extractS50CruLines(existing) : const <String>[];
    if (ours && lines.contains(kGuardCronLine)) return;
    // The router's own script is kept once, as a watchdog deploy keeps it, so UNINSTALL can put it back.
    final backup = originalScriptBackupPath(kS50Path);
    await read("[ -f '$kS50Path' ] && [ ! -f '$backup' ] && ! grep -q '$kOurScriptSignature' '$kS50Path' && "
        "cp -p '$kS50Path' '$backup' || true");
    final body = buildS50Script([...lines.where((l) => l != kGuardCronLine), kGuardCronLine]);
    for (final cmd in heredocWriteCommands(kS50Path, body)) {
      await run(cmd);
    }
    await run("chmod 700 '$kS50Path'");
    final size = int.tryParse((await read("wc -c < '$kS50Path' 2>/dev/null | tr -d ' '")).trim()) ?? 0;
    if (size != writtenByteCount(body)) throw Exception('the router holds $size of the ${writtenByteCount(body)} bytes of $kS50Path');
  }

  /// Writes the script only when what is on the router differs, so an unchanged guard costs one
  /// read and no flash write. Verified by size afterwards, as every other file the app writes is.
  Future<void> install() async {
    // `|| true`: on a router that has never had the guard there is no file, and a read that exits
    // non-zero is logged as a failed command - which is how a normal first install used to read.
    final current = await read("cat '$kGuardScriptPath' 2>/dev/null || true");
    if (current.trim() == kGuardScript.trim()) return;
    await run("mkdir -p '$kRouterAppDir'");
    for (final cmd in heredocWriteCommands(kGuardScriptPath, kGuardScript)) {
      await run(cmd);
    }
    await run("chmod 755 '$kGuardScriptPath'");
    final expected = writtenByteCount(kGuardScript);
    final size = int.tryParse((await read("wc -c < '$kGuardScriptPath' 2>/dev/null | tr -d ' '")).trim()) ?? 0;
    if (size != expected) {
      throw Exception('the router holds $size of the $expected bytes of $kGuardScriptPath');
    }
  }

  /// Removes every guard rule. Used by UNINSTALL, before the script goes with the app's folder.
  Future<void> clear() => read("[ -x '$kGuardScriptPath' ] && '$kGuardScriptPath' clear");
}
