// fail_closed_guard.dart - keeps a device pinned to a tunnel off the internet while that tunnel is down.
//
// This program is free software: you can redistribute it and/or modify it under the terms
// of the GNU General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program.
// If not, see https://www.gnu.org/licenses/.
//
// Copyright (C) 2026 Andrew Newbury.
//
// Stock firmware has no kill switch, and on its own it does not quite fail closed. Measured
// 2026-09-24 with a device pinned to wgc1 (ARCHITECTURE.md "The fail-closed guard"):
//
//   - a tunnel whose server stops answering blocks the device, which is right;
//   - a watchdog rebuild let one reply out through the default connection, in the second the
//     firmware spent rebuilding the tunnel's routing table;
//   - a DISABLE let the device out for as long as the tunnel was off, through the default
//     connection, and in the clear when that is the plain internet.
//
// The firmware's own tunnel table can't close that gap: it rebuilds it on every restart, and fills
// it with a copy of main - the WAN default, and host routes via the WAN to the router's own DNS
// servers. So the guard keeps a table of its own per tunnel, holding the tunnel's default and the
// router's local routes and never a route out of the WAN, and two rules per pinned device: rule 90
// looks the device up in that table, and rule 91 blackholes whatever it can't route (ID-364).
// When a tunnel stops, the kernel removes its routes from every table, ours included, so the
// device is blocked with nothing having to run. Rules survive everything but a reboot and
// `restart_net_and_phy`, and the boot hook, which stock calls with `firewall-start` whenever its
// routing changes, runs the guard again after both. Merlin's kill switch has the same shape: a
// deny rule that stays put, after a lookup, kept true by events rather than a timer.
//
// Stock only. Merlin has a real kill switch, and device assignment is a stock feature here.

import 'firmware.dart' show kRouterAppDir, kS50Path, kStockBootDir, originalScriptBackupPath;
import 'router_watchdog.dart' show heredocWriteCommands, writtenByteCount;
import 's50_template.dart' show buildS50Script, extractS50CruLines, kLegacyGuardCronTag;

export 's50_template.dart' show kLegacyGuardCronTag;

/// Where the guard script lives on the router. The watchdog script and the boot hook call it by
/// this path, and only if it is there.
const String kGuardScriptPath = '$kRouterAppDir/guard.sh';

/// The guard's own table for slot N is `kGuardTableBase + N`, 201 to 205: free on stock, which
/// numbers its tunnel tables by profile from 1 to 9. Rule 90 looks a pinned device up in it.
const int kGuardTableBase = 200;

/// The table rule 90 sends a device pinned to [slot] to.
int guardTableForSlot(int slot) => kGuardTableBase + slot;

/// Marks the app's own copy of an init script; the same line RouterWatchdog looks for.
const String kOurScriptSignature = 'auto-generated by cfg-pia-wg';

/// The guard script. Idempotent: run it as often as you like, and it changes only what is wrong.
///
/// Priorities 90 and 91 are the app's alone - the firmware's per-device rules sit at 100 and its
/// default connection at 10000 - so anything found at 90 or 91 is the guard's to keep or remove.
/// The user's choice to block pings out of the internet connection for the whole network (ID-348):
/// `1` for on. The filter can't hold pings for one device, so it isn't part of pinning.
const String kPingBlockKey = 'cfg_pia_wg_lw_icmp';

/// The second layer of the guard: stock's own Network Services Filter (ID-348), as a shell function
/// `lw_sync "<addresses>"`. Part of [kGuardScript], and run on its own by UNINSTALL in case the script
/// is gone. Prints one line: `filter held N of M`, `filter refused: <why>`, or nothing when no
/// device is pinned; and `filter scheduled` when the user's filter has a timetable.
const String kFilterSyncFunctions = r'''
# ---- The second layer: the router's own Network Services Filter (ID-348) ------------------------
# The rules above live in the kernel, so a reboot clears them, and stock runs no add-on code until
# the USB disk is mounted, about 30 s into a boot: measured 2026-09-30, a pinned device reached the
# internet directly for 3 to 6 seconds on 4 of 6 boots. And restart_net_and_phy clears them until
# the guard's next run. The Network Services Filter is the firmware's own, kept in NVRAM and
# applied at boot before the WAN is up, and it builds
#     -A FORWARD -s <ip> -i br0 -o <WAN> -p tcp|udp -j DROP
# which drops a device's traffic out of the internet connection only, never through a tunnel.
# Measured with it: 0 of 4 boots leaked; a device forced out of the WAN by hand was blocked; 80
# entries built 80 rules; a tunnel restart keeps them.
#
# The app adds and removes only its own entries, remembered as ip/PROTO in cfg_pia_wg_lwlist, and
# never uses the filter as an allow list, where listing a device would let it out. Pings can only
# be filtered for the whole network (filter_lw_icmp_x), so that is the user's choice,
# cfg_pia_wg_lw_icmp=1, off by default; cfg_pia_wg_lw_icmp8 remembers that the app added the 8.
lw_in() { case " $2 " in *" $1 "*) return 0 ;; esac; return 1; }
lw_say() { logger -t cfg-pia-wg "$1"; }
lw_sync() {
  set -f
  LWWANT=" $(echo $1) "
  LWOURS=" $(nvram get cfg_pia_wg_lwlist) "
  LWCUR="$(nvram get filter_lwlist)"
  LWREFUSED=""
  # Entries that are not the app's: the user's own.
  LWTHEIRS=""
  for E in $(echo "$LWCUR" | tr '<' ' '); do
    IP="${E%%>*}"; PR="${E##*>}"
    [ "$E" = "$IP>>>>$PR" ] && lw_in "$IP/$PR" "$LWOURS" && continue
    LWTHEIRS="$LWTHEIRS $E"
  done
  if [ "$LWWANT" != "  " ]; then
    if [ "$(nvram get fw_enable_x)" != 1 ]; then
      LWREFUSED="the router's firewall is off"
    elif [ "$(nvram get filter_lw_default_x)" = DROP ]; then
      LWREFUSED="it is an allow list, where listing a device would let it out"
    elif [ "$(nvram get fw_lw_enable_x)" != 1 ] && [ -n "$LWTHEIRS" ]; then
      LWREFUSED="it is off, and turning it on would also apply the entries you made"
    fi
    [ -n "$LWREFUSED" ] && LWWANT="  "
  fi
  # The new list: everything as it was, less the app's entries for devices no longer pinned, plus
  # the ones missing. An entry the user made for a pinned device is left theirs.
  LWNORM=""; LWNEW=""
  for E in $(echo "$LWCUR" | tr '<' ' '); do
    LWNORM="$LWNORM<$E"
    IP="${E%%>*}"; PR="${E##*>}"
    [ "$E" = "$IP>>>>$PR" ] && lw_in "$IP/$PR" "$LWOURS" && ! lw_in "$IP" "$LWWANT" && continue
    LWNEW="$LWNEW<$E"
  done
  LWNOURS=""
  for IP in $LWWANT; do
    for PR in TCP UDP; do
      case "$LWNEW<" in
        *"<$IP>>>>$PR<"*) lw_in "$IP/$PR" "$LWOURS" && LWNOURS="$LWNOURS $IP/$PR" ;;
        *) LWNEW="$LWNEW<$IP>>>>$PR"; LWNOURS="$LWNOURS $IP/$PR" ;;
      esac
    done
  done
  LWNOURS="$(echo $LWNOURS)"
  CH=0
  [ "$LWNEW" != "$LWNORM" ] && { nvram set filter_lwlist="$LWNEW"; CH=1; }
  if [ "$LWNOURS" != "$(echo $LWOURS)" ]; then
    if [ -n "$LWNOURS" ]; then nvram set cfg_pia_wg_lwlist="$LWNOURS"; else nvram unset cfg_pia_wg_lwlist; fi
    CH=1
  fi
  if [ "$LWWANT" != "  " ]; then
    [ "$(nvram get fw_lw_enable_x)" != 1 ] && { nvram set fw_lw_enable_x=1; nvram set cfg_pia_wg_lw_on=1; CH=1; }
  elif [ -n "$(nvram get cfg_pia_wg_lw_on)" ]; then
    # Off again only if the app turned it on and nothing is left in it; entries the user added
    # since are theirs, and stay working.
    [ -z "$LWNEW" ] && nvram set fw_lw_enable_x=0
    nvram unset cfg_pia_wg_lw_on; CH=1
  fi
  LWICMP=" $(nvram get filter_lw_icmp_x) "
  if [ "$LWWANT" != "  " ] && [ "$(nvram get cfg_pia_wg_lw_icmp)" = 1 ]; then
    lw_in 8 "$LWICMP" || { nvram set filter_lw_icmp_x="$(echo $LWICMP 8)"; nvram set cfg_pia_wg_lw_icmp8=1; CH=1; }
  elif [ -n "$(nvram get cfg_pia_wg_lw_icmp8)" ]; then
    LWI=""; for T in $LWICMP; do [ "$T" = 8 ] || LWI="$LWI $T"; done
    nvram set filter_lw_icmp_x="$(echo $LWI)"; nvram unset cfg_pia_wg_lw_icmp8; CH=1
  fi
  set +f
  # Read back from the firewall itself, not the settings.
  lw_held() {
    F="$(iptables -S FORWARD 2>/dev/null)"; N=0
    for IP in $LWWANT; do
      R="$(echo "$IP" | sed 's/[.]/[.]/g')"
      [ "$(echo "$F" | grep -cE -- "-s $R/32 -i br0 -o [^ ]+ -p (tcp|udp) -j DROP")" -ge 2 ] && N=$((N + 1))
    done
    echo "$N"
  }
  LWM=0; for IP in $LWWANT; do LWM=$((LWM + 1)); done
  lw_read() { LWHELD="$(lw_held)"; }
  # A firewall restart is asked for only when the list itself changed (ID-364). The guard runs on
  # firewall-start, which every restart raises, so asking again whenever the read-back came up short
  # would loop; and a restart the service queue dropped is put right by the router's next firewall
  # restart, whatever causes it, since the list is already right in NVRAM. A run with nothing to
  # change reads the chain once (ID-362).
  if [ "$CH" = 1 ]; then
    nvram commit
    service restart_firewall >/dev/null 2>&1
    if [ "$LWM" -gt 0 ]; then
      lw_say "Network Services Filter: $LWM pinned device(s) kept off the internet connection outside their tunnel"
    else
      lw_say "Network Services Filter: the app's entries taken out"
    fi
    # Report what the firewall holds once it has been rebuilt, not what was asked for.
    lw_read; W=0
    while [ "$W" -lt "${LW_WAIT:-15}" ] && [ "$LWHELD" -lt "$LWM" ]; do sleep 1; W=$((W + 1)); lw_read; done
  else
    lw_read
  fi
  if [ -n "$LWREFUSED" ]; then
    echo "filter refused: $LWREFUSED"
  elif [ "$LWM" -gt 0 ]; then
    echo "filter held $LWHELD of $LWM"
    [ "$(nvram get filter_lw_date_x)" = 1111111 ] && [ "$(nvram get filter_lw_time_x)" = 00002359 ] &&
      [ "$(nvram get filter_lw_time2_x)" = 00002359 ] || echo "filter scheduled"
  fi
}
''';

/// [kFilterSyncFunctions] without its comments, then `lw_sync ""`: takes the app's entries out of
/// the filter and puts it back as the app found it. What UNINSTALL runs directly.
final String kFilterClearCommand = [
  for (final l in kFilterSyncFunctions.split('\n'))
    if (l.trim().isNotEmpty && !l.trimLeft().startsWith('#')) l,
  'lw_sync ""',
].join('\n');

const String kGuardScript = r'''#!/bin/sh
# guard.sh - auto-generated by cfg-pia-wg; *do* *not* edit.
#
# Keeps every device pinned to a WireGuard tunnel off the internet whenever that tunnel is not
# carrying it: expired, being rebuilt, or switched off (ID-213, ID-364). Two rules per pinned
# device, and one table per tunnel that the guard owns:
#
#   90: from <ip> lookup <200 + slot>   our table: the tunnel's default and the router's local routes
#   91: from <ip> blackhole             reached whenever our table can't route it
#
# Our table never holds a route out of the WAN, so nothing in it can leak, and nothing in it goes
# stale when the WAN or the router's DNS servers change. When the tunnel stops, the kernel takes its
# routes out of every table, ours included, so the device is blocked with nothing having to run:
# measured 2026-10-03, the route was gone 0.26 s after stop_vpnc.
#
# Worked out afresh from vpnc_dev_policy_list on every run, so a pin made or removed in the web
# interface is followed at the next run. "guard.sh clear" removes every guard rule and table.
# "guard.sh soon" is for events: it waits until 10 s have passed without a newer request, then runs
# once, so a burst of firewall-start calls costs one run - well clear of the 1 to 2 s spacing at
# which back-to-back runs crash the firmware's asd daemon (ID-361).

if [ "$1" = "soon" ]; then
  NEXT="${GUARD_NEXT:-/tmp/cfg-pia-wg-guard.next}"
  echo $$ > "$NEXT"
  sleep "${GUARD_SOON:-10}"
  [ "$(cat "$NEXT" 2>/dev/null)" = "$$" ] || exit 0
  set --
fi

# One run at a time, or two would add the same rule.
LOCK="${GUARD_LOCK:-/tmp/cfg-pia-wg-guard.lock}"
W=0
until mkdir "$LOCK" 2>/dev/null; do
  W=$((W + 1))
  # Ten seconds is far longer than a run takes, so a lock that old was left by a killed run. If it
  # still can't be taken, another run has just taken it, and that run does the work.
  if [ "$W" -ge 10 ]; then rm -rf "$LOCK"; mkdir "$LOCK" 2>/dev/null || exit 0; break; fi
  sleep 1
done
trap 'rmdir "$LOCK" 2>/dev/null' EXIT
trap 'exit 1' INT TERM

say() { logger -t cfg-pia-wg "$1"; }

# Every "ip>table" that should be guarded: an enabled policy record naming a WireGuard profile, the
# profile's slot turned into our table for it. And every address pinned to a profile that no longer
# exists at all: deleted in the web interface, which leaves the pin behind. The firmware's rule sends
# it to an empty table and on to the default connection, so it gets rule 91 alone: no tunnel to use,
# so nothing. A pin to Internet is index 0, and a pin to an OpenVPN profile names a profile that
# exists; neither is caught. A vpnc_clientlist record is desc>protocol>slot>...>table, table 7th.
WANT=""
ORPHAN=""
if [ "$1" != "clear" ]; then
  CL="$(nvram get vpnc_clientlist)"; export CL
  WANT="$(nvram get vpnc_dev_policy_list | tr '<' '\n' | awk -F'>' '
    BEGIN { n = split(ENVIRON["CL"], r, "<"); for (i = 1; i <= n; i++) { split(r[i], f, ">"); if (f[2] == "WireGuard" && f[3] != "" && f[7] != "") s[f[7]] = 200 + f[3] } }
    $1 == "1" && $2 != "" && ($4 in s) { print $2 ">" s[$4] }')"
  ORPHAN="$(nvram get vpnc_dev_policy_list | tr '<' '\n' | awk -F'>' '
    BEGIN { n = split(ENVIRON["CL"], r, "<"); for (i = 1; i <= n; i++) { split(r[i], f, ">"); if (f[7] != "") a[f[7]] = 1 } }
    $1 == "1" && $2 != "" && $4 != "" && $4 != "0" && !($4 in a) { print $2 }')"
fi

held90() { ip rule show | awk '$1 == "90:" {ip = ""; t = ""; for (i = 2; i < NF; i++) {if ($i == "from") ip = $(i + 1); if ($i == "lookup") t = $(i + 1)} if (ip != "") print ip ">" t}'; }
held91() { ip rule show | awk '$1 == "91:" {for (i = 2; i < NF; i++) if ($i == "from") print $(i + 1)}'; }
wanted_ip() { echo "$WANT" | awk -F'>' -v ip="$1" '$1 == ip {f = 1} END {exit !f}'; }
orphan_ip() { echo "$ORPHAN" | grep -qxF "$1"; }
drop() { N=0; while [ "$N" -lt 16 ] && ip rule del from "$1" priority "$2" 2>/dev/null; do N=$((N + 1)); done; }
# The device as DEVICES names it, then its address: the user's name, else the detected
# one, else the address alone (ID-262).
name_of() {
  M="$(nvram get dhcp_staticlist | tr '<' '\n' | awk -F'>' -v a="$1" '$2 == a {print toupper($1); exit}')"
  D=""
  [ -n "$M" ] && D="$(nvram get custom_clientlist | tr '<' '\n' | awk -F'>' -v m="$M" 'toupper($2) == m && $1 != "" {print $1; exit}')"
  [ -z "$D" ] && [ -n "$M" ] && [ -x /jffs/cfg-pia-wg/jq ] && D="$(/jffs/cfg-pia-wg/jq -r --arg m "$M" 'to_entries[] | select((.key | ascii_upcase) == $m) | .value.name // empty' 2>/dev/null < /jffs/nmp_cl_json.js | head -1)"
  echo "${D:+$D }$1"
}

# Rules from before build 491, all gone now (ID-364): 88 and 89, for the addresses the firmware's
# table sent out of the WAN (ID-347), which our table can't. A 90 that looked up the firmware's own
# table through suppress_prefixlength 0 isn't wanted either, and the loop below replaces it.
for P in 88 89; do
  for IP in $(ip rule show | awk -v p="$P:" '$1 == p {for (i = 2; i < NF; i++) if ($i == "from") print $(i + 1)}' | sort -u); do
    drop "$IP" "$P"
  done
done

# Take away what is no longer wanted, wanted differently, or held more than once.
H90="$(held90)"
for E in $(echo "$H90" | sort -u); do
  if ! echo "$WANT" | grep -qxF "$E" || [ "$(echo "$H90" | grep -cxF "$E")" -gt 1 ]; then
    drop "${E%>*}" 90
    wanted_ip "${E%>*}" || say "Fail-closed guard removed for $(name_of "${E%>*}")"
  fi
done
H91="$(held91)"
for IP in $(echo "$H91" | sort -u); do
  if ! { wanted_ip "$IP" || orphan_ip "$IP"; } || [ "$(echo "$H91" | grep -cxF "$IP")" -gt 1 ]; then drop "$IP" 91; fi
done

# Add what is missing. The drop rule goes in first, so a half-added guard fails closed, not open.
FAIL=0
H90="$(held90)"
H91="$(held91)"
for E in $WANT; do
  IP="${E%>*}"
  T="${E#*>}"
  echo "$H91" | grep -qxF "$IP" || ip rule add from "$IP" blackhole priority 91 || FAIL=$((FAIL + 1))
  if ! echo "$H90" | grep -qxF "$E"; then
    if ip rule add from "$IP" lookup "$T" priority 90; then
      say "Fail-closed guard on for $(name_of "$IP") (wgc$((T - 200)))"
    else
      FAIL=$((FAIL + 1))
    fi
  fi
done
H91="$(held91)"
for IP in $ORPHAN; do
  echo "$H91" | grep -qxF "$IP" && continue
  if ip rule add from "$IP" blackhole priority 91; then
    say "Fail-closed guard: $(name_of "$IP") is pinned to a VPN profile that no longer exists, so it is kept off the internet"
  else
    FAIL=$((FAIL + 1))
  fi
done

# Our table for each tunnel with a pin. While the tunnel is up it holds the router's local routes -
# its LAN and guest bridges, loopback, its own WireGuard and OpenVPN servers - and the tunnel's
# default. The whitelist is by device, so an interface nobody thought of is left out, which fails
# closed, and nothing via the WAN is ever copied. `replace` changes nothing that is already right,
# so a run with nothing to do leaves the table alone. While the tunnel is down its default has gone
# with it and the device falls through to 91, so there is nothing to add.
KEEP=' dev (br|lo|wgs|tun)[0-9.]*( |$)'
LOCAL="$(ip route show table main | grep -E "$KEEP")"
UP="$(ip -o link show up)"
for N in 1 2 3 4 5; do
  T=$((200 + N))
  if [ "$1" = "clear" ] || ! echo "$WANT" | grep -q ">$T\$"; then
    ip route flush table $T 2>/dev/null
    continue
  fi
  # Anything the guard would not have put there goes, whatever put it there, so the table never
  # routes out of the WAN, with the tunnel up or down.
  ip route show table $T 2>/dev/null | grep -vE "^default dev wgc$N( |\$)" | grep -vE "$KEEP" |
    while read -r R; do [ -n "$R" ] && ip route del $R table $T 2>/dev/null; done
  echo "$UP" | grep -q " wgc$N:" || continue
  echo "$LOCAL" | while read -r R; do [ -n "$R" ] && ip route replace $R table $T 2>/dev/null; done
  ip route replace default dev wgc$N table $T 2>/dev/null
done

''' + kFilterSyncFunctions + r'''
# Every pinned device, the orphans included; none in clear mode, which takes the app's own out.
lw_sync "$(for E in $WANT; do echo "${E%>*}"; done; echo "$ORPHAN")"

# Counted from the kernel, not from what was asked for (ID-320): a device is guarded when it holds
# exactly one 90 rule into our table for its tunnel, and one 91 blackhole.
RULES="$(ip rule show)"
TOTAL=0; OK=0
for E in $WANT; do
  IP="${E%>*}"; T="${E#*>}"; TOTAL=$((TOTAL + 1))
  [ "$(echo "$RULES" | grep -cE "^90:.*from $IP lookup $T( |\$)")" = 1 ] || continue
  [ "$(echo "$RULES" | grep -c "^91:.*from $IP blackhole")" = 1 ] && OK=$((OK + 1))
done
for IP in $ORPHAN; do
  TOTAL=$((TOTAL + 1))
  [ "$(echo "$RULES" | grep -c "^91:.*from $IP blackhole")" = 1 ] && OK=$((OK + 1))
done
echo "guarded $OK of $TOTAL"
[ "$FAIL" -eq 0 ] || { echo "failed $FAIL"; say "Fail-closed guard: $FAIL rule(s) could not be added"; exit 1; }
exit 0
''';

typedef GuardLog = void Function(String message, {bool isError, bool isSuccess, bool isWarning});

/// Installs and runs [kGuardScript] over an existing SSH session.
///
/// Takes the caller's own read and run so it goes through the same command path, logging and test
/// fakes as everything else: [read] never throws, [run] throws on a non-zero exit.
class FailClosedGuard {
  FailClosedGuard({required this.read, required this.run, this.onLog});

  final Future<String> Function(String cmd) read;
  final Future<String> Function(String cmd) run;
  final GuardLog? onLog;

  /// Puts the script in place if it is missing or out of date, runs it, and returns how many
  /// devices it now guards.
  ///
  /// Never throws: a guard that could not be put in place must not stop the action it follows,
  /// whether that is an assignment, a DISABLE or a DELETE. It returns null instead, after saying
  /// plainly in the app log what that means. [quiet] leaves out the line reporting success, for
  /// callers that run it on every screen refresh.
  Future<int?> ensure({bool quiet = false}) async {
    try {
      await install();
      final out = await run("'$kGuardScriptPath'");
      // "guarded N of M": N is what the kernel holds, counted after the run, not what was asked for
      // (ID-320). An older script says only "guarded N".
      final m = RegExp(r'guarded (\d+)(?: of (\d+))?').firstMatch(out);
      final count = int.tryParse(m?.group(1) ?? '');
      final total = int.tryParse(m?.group(2) ?? '') ?? count;
      if (count != null && total != null && count < total) {
        onLog?.call(
          'The fail-closed guard is complete for only $count of $total pinned devices. Until it is, the others '
          'can reach the internet outside their tunnel.',
          isWarning: true,
        );
      } else if (!quiet && count != null && count > 0) {
        onLog?.call('Fail-closed guard in place for $count pinned device${count == 1 ? '' : 's'}.');
      }
      _reportFilter(out, quiet: quiet);
      // No count means the run's output was lost, not that nothing is pinned: leave the boot hook as
      // it is rather than change it from under pinned devices.
      if (total == null) return count;
      await _persist(total);
      return count;
    } catch (e) {
      onLog?.call(
        'The fail-closed guard could not be put in place ($e). Until it is, a device pinned to a tunnel '
        'can reach the internet through the default connection while that tunnel is down.',
        isWarning: true,
      );
      return null;
    }
  }

  /// What the script said about its second layer, the router's Network Services Filter (ID-348).
  /// A refusal or a shortfall is always reported; a filter that holds every device only when not
  /// [quiet].
  void _reportFilter(String out, {required bool quiet}) {
    final refused = RegExp(r'filter refused: (.+)').firstMatch(out)?.group(1)?.trim();
    if (refused != null) {
      onLog?.call(
        "The router's Network Services Filter can't be used to hold pinned devices: $refused. "
        'The guard still works, but for the first half-minute or so after the router starts, before the guard can '
        'run, a pinned device can reach the internet directly.',
        isWarning: true,
      );
      return;
    }
    final m = RegExp(r'filter held (\d+) of (\d+)').firstMatch(out);
    if (m == null) return;
    final held = int.parse(m.group(1)!), of = int.parse(m.group(2)!);
    if (held < of) {
      onLog?.call(
        "The router's Network Services Filter holds only $held of $of pinned devices so far. The rest take "
        'effect the next time the router restarts its firewall, which it does whenever its connection changes.',
        isWarning: true,
      );
    } else if (!quiet) {
      onLog?.call("The router's Network Services Filter keeps them off the internet connection outside their "
          'tunnel, from the moment the router starts.');
    }
    if (out.contains('filter scheduled')) {
      onLog?.call(
        "The router's Network Services Filter has a timetable (Firewall, Network Services Filter), so it holds "
        'pinned devices only at the times it sets.',
        isWarning: true,
      );
    }
  }

  /// Keeps the guard running without the app (ID-315, ID-364). The boot hook runs it at boot and, on
  /// every `firewall-start` the firmware raises - a firewall restart, a tunnel started or stopped, a
  /// WAN reconnect, `restart_net_and_phy` - asks it for one run once things settle. Whenever a device
  /// is pinned the hook is put in place and kept current; when none is, a hook that is already the
  /// app's is still brought up to date, since watchdogs use it too.
  ///
  /// Builds 480 to 490 ran the guard from a cron entry every minute instead (ID-316). Repair after
  /// the fact, and at every watchdog check it ran the guard twice inside a second, which is what
  /// crashed the firmware's `asd` (ID-361). The entry is taken out here, from the router, and
  /// rebuilding the hook takes out its line there.
  Future<void> _persist(int pinned) async {
    if ((await read("cru l | grep -c '#$kLegacyGuardCronTag#'")).trim() != '0') await run('cru d $kLegacyGuardCronTag');
    final existing = await read("cat '$kS50Path' 2>/dev/null || true");
    final ours = existing.contains(kOurScriptSignature);
    if (!ours) {
      if (pinned == 0) return;
      // The boot hook lives where stock runs it: Download Master's init directory, on USB storage.
      if ((await read("[ -d '$kStockBootDir' ] && echo yes || echo no")).trim() != 'yes') {
        onLog?.call(
          'The fail-closed guard will not survive a reboot: $kStockBootDir is missing, so the app has no boot hook. '
          'Install Download Master (README section 4), and leave it installed and enabled. Without the hook, after '
          'a reboot and until the app is next used, pinned devices can reach the internet outside their tunnel '
          'whenever it is down.',
          isWarning: true,
        );
        return;
      }
      // The router's own script is kept once, as a watchdog deploy keeps it, so UNINSTALL can put it back.
      final backup = originalScriptBackupPath(kS50Path);
      await read("[ -f '$kS50Path' ] && [ ! -f '$backup' ] && ! grep -q '$kOurScriptSignature' '$kS50Path' && "
          "cp -p '$kS50Path' '$backup' || true");
    }
    final body = buildS50Script(ours ? extractS50CruLines(existing) : const []);
    if (ours && body.trim() == existing.trim()) return;
    for (final cmd in heredocWriteCommands(kS50Path, body)) {
      await run(cmd);
    }
    await run("chmod 700 '$kS50Path'");
    final size = int.tryParse((await read("wc -c < '$kS50Path' 2>/dev/null | tr -d ' '")).trim()) ?? 0;
    if (size != writtenByteCount(body)) throw Exception('the router holds $size of the ${writtenByteCount(body)} bytes of $kS50Path');
  }

  /// Writes the script only when what is on the router differs, so an unchanged guard costs one
  /// read and no flash write. Verified by size afterwards, as every other file the app writes is.
  Future<void> install() async {
    // `|| true`: on a router that has never had the guard there is no file, and a read that exits
    // non-zero is logged as a failed command - which is how a normal first install used to read.
    final current = await read("cat '$kGuardScriptPath' 2>/dev/null || true");
    if (current.trim() == kGuardScript.trim()) return;
    await run("mkdir -p '$kRouterAppDir'");
    for (final cmd in heredocWriteCommands(kGuardScriptPath, kGuardScript)) {
      await run(cmd);
    }
    await run("chmod 755 '$kGuardScriptPath'");
    final expected = writtenByteCount(kGuardScript);
    final size = int.tryParse((await read("wc -c < '$kGuardScriptPath' 2>/dev/null | tr -d ' '")).trim()) ?? 0;
    if (size != expected) {
      throw Exception('the router holds $size of the $expected bytes of $kGuardScriptPath');
    }
  }

  /// Removes every guard rule. Used by UNINSTALL, before the script goes with the app's folder.
  Future<void> clear() => read("[ -x '$kGuardScriptPath' ] && '$kGuardScriptPath' clear");
}
