#!/bin/sh
# S50asuslighttpd - auto-generated by cfg-pia-wg; *do* *not* edit.
# Stub. No functionality wanted here. Always returns instantly
# regardless of trigger (start, firewall-start, firewall-restart,
# stop, restart, lighttpd-restart).
exit 0
