#!/bin/sh
# S50downloadmaster - auto-generated by cfg-pia-wg; *do* *not* edit.
# Minimal replacement for the stock Download Master init script.
# At boot (start): put our cron jobs back, and run the fail-closed guard.
# On firewall-start - which stock raises at boot, on a firewall restart, when a tunnel starts or
# stops, on a WAN reconnect and on restart_net_and_phy (measured 2026-10-03) - ask the guard for
# one run once things settle, in the background, so the firmware waits for nothing (ID-364).
# Every other trigger (firewall-restart, restart, stop, lighttpd-restart,
# bt-restart, dir-change) returns instantly so VPN up/down events are never delayed.

# bootup/powercycle requires a delay otherwise the boot process is blocked
# and the VPN gets stuck in a "connecting" state.
BOOT_FLAG=/tmp/.dm_boot_delay_done
if [ ! -f "$BOOT_FLAG" ]; then
    touch "$BOOT_FLAG"
    sleep 10
fi

if [ "$1" = "firewall-start" ]; then
  [ -x /jffs/cfg-pia-wg/guard.sh ] && /jffs/cfg-pia-wg/guard.sh soon </dev/null >/dev/null 2>&1 &
  exit 0
fi
[ "$1" = "start" ] || exit 0
  # Add cru jobs back after rebooting or power cycle
  # ********** REPLACEMENT START **********
  # 1 to N cruCheckLine entries
  # 1 to N cruRotateLine entries
  # ********** REPLACEMENT END **********
  # Put the fail-closed guard back: a reboot clears its rules (ID-213).
  [ -x /jffs/cfg-pia-wg/guard.sh ] && /jffs/cfg-pia-wg/guard.sh >/dev/null 2>&1
exit 0